#### 데이터 준비

In [1]:
from sklearn import datasets
X, y = datasets.make_classification(n_samples=10000, n_features=10, random_state=0)
# n_samples 표본 데이터 수, n_features 독립변수의 수

In [2]:
display(X[0], y[0])

array([ 2.06062692,  1.09749627, -0.57541347, -0.58559079, -1.0957789 ,
       -0.87938396, -0.69878976,  1.36367022, -0.96010017, -0.58659684])

1

#### 데이터 분할

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
#X는 대문자 : 행렬, y는 소문자 : 벡터를 의미, Row 데이터를 학습용과 테스트 용으로 랜덤하게 쪼갠다.

#### 모형 생성 - 로지스틱 회귀분석

In [17]:
# 로지스틱 회귀분석 예
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train) # 학습데이터를 모델에 적용
# 이것으로 학습이 마침

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

#### 모형 평가

In [18]:
model.score(X_test, y_test) # 학습할때와 다르게 test용 데이터를 사용하여 평가

0.832

In [26]:
# 미래에 아래와 같은 데이터가 들어오면 예측을 할 수 있다
X_unknown = [[2.01, 2.36, 4.18, 1.24, -2.37, 4.21, 2.10, 2.95, 3.08, -1.87]]
model.predict(X_unknown)

array([1])

In [73]:
model.predict_proba(X_unknown)[:,1]

array([0.94545629])

## 머신러닝 BASIC

In [29]:
import pandas as pd
import numpy as np

In [30]:
df = pd.read_csv("data/data_pepTestCustomers.csv")
df.head()

id   age  sex  region   income  married  children  car  save_act  \
0  ID12101  48.0    0       0  17546.0        0         1    0         0   
1  ID12102  40.0    1       3  30085.1        1         3    1         0   
2  ID12103   NaN    0       0  16575.4        1         0    1         1   
3  ID12104  23.0    0       3  20375.4        1         3    0         0   
4  ID12105  57.0    0       1  50576.3        1         0    0         1   

   current_act  mortgage  pep  
0            0         0    1  
1            1         1    0  
2            1         0    0  
3            1         0    0  
4            0         0    0

In [31]:
new = pd.read_csv("data/data_pepNewCustomers.csv")
new.head()

id  age  sex  region    income  married  children  car  save_act  \
0  ID12701   23    1       0  18766.90        1         0    1         1   
1  ID12702   30    1       1   9915.67        0         1    0         1   
2  ID12703   45    0       1  21881.60        0         0    1         1   
3  ID12704   50    1       3  46794.40        1         2    0         1   
4  ID12705   41    0       0  20721.10        1         0    1         1   

   current_act  mortgage  
0            0         1  
1            0         1  
2            1         0  
3            0         1  
4            1         0

## 데이터 나누기 : 학습용, 평가용

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           600 non-null    object 
 1   age          540 non-null    float64
 2   sex          600 non-null    int64  
 3   region       600 non-null    int64  
 4   income       600 non-null    float64
 5   married      600 non-null    int64  
 6   children     600 non-null    int64  
 7   car          600 non-null    int64  
 8   save_act     600 non-null    int64  
 9   current_act  600 non-null    int64  
 10  mortgage     600 non-null    int64  
 11  pep          600 non-null    int64  
dtypes: float64(2), int64(9), object(1)
memory usage: 56.4+ KB


In [33]:
# 평균값으로 결측값 대체하기
df.age.fillna(round(df.age.mean(),0), inplace=True)
df.head()

id   age  sex  region   income  married  children  car  save_act  \
0  ID12101  48.0    0       0  17546.0        0         1    0         0   
1  ID12102  40.0    1       3  30085.1        1         3    1         0   
2  ID12103  43.0    0       0  16575.4        1         0    1         1   
3  ID12104  23.0    0       3  20375.4        1         3    0         0   
4  ID12105  57.0    0       1  50576.3        1         0    0         1   

   current_act  mortgage  pep  
0            0         0    1  
1            1         1    0  
2            1         0    0  
3            1         0    0  
4            0         0    0

In [34]:
# 데이터 나누기
from sklearn.model_selection import train_test_split

In [35]:
# scikit-learn에서는 속성과 클래스를 분리하여야 한다.
X = df.drop(['id','pep'], axis=1) 
Y = df['pep']                    
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=0)

In [36]:
# 지정한 비율(75:25)로 데이터가 잘 나누어졌는지 확인
display(X_train.shape, X_test.shape)
display(y_train.shape, y_test.shape)
X_train.head()
#y_train.head()

(450, 10)

(150, 10)

(450,)

(150,)

age  sex  region   income  married  children  car  save_act  \
46   50.0    0       0  13283.9        0         1    1         1   
263  60.0    0       0  46358.4        1         0    1         1   
458  18.0    1       2  13700.2        0         1    0         1   
230  59.0    0       0  30189.4        1         0    1         0   
107  23.0    1       0  13039.9        1         0    0         0   

     current_act  mortgage  
46             1         0  
263            1         1  
458            1         0  
230            1         1  
107            1         0

## 학습

In [37]:
# 학습 알고르즘 선정 : 의사결정나무
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier(max_depth=6, random_state=0)

In [38]:
# 의사결정나무 알고리즘에 학습용 데이터를 학습한다.
tree.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=6, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

## 평가

In [39]:
display(tree.score(X_train, y_train))
display(tree.score(X_test, y_test))

0.9355555555555556

0.8733333333333333

- 평가결과 모델의 정확율이 87.3% 로 나왔습니다. 

## 전개(적용)

In [40]:
new = pd.read_csv("data/data_pepNewCustomers.csv")
new.head()

id  age  sex  region    income  married  children  car  save_act  \
0  ID12701   23    1       0  18766.90        1         0    1         1   
1  ID12702   30    1       1   9915.67        0         1    0         1   
2  ID12703   45    0       1  21881.60        0         0    1         1   
3  ID12704   50    1       3  46794.40        1         2    0         1   
4  ID12705   41    0       0  20721.10        1         0    1         1   

   current_act  mortgage  
0            0         1  
1            0         1  
2            1         0  
3            0         1  
4            1         0

In [41]:
tree.predict(new.loc[:,'age':'mortgage'])

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0])

In [76]:
pred = tree.predict_proba(new.loc[:,'age':'mortgage'])[:,1]
pred

array([0.12      , 0.        , 1.        , 1.        , 0.18604651,
       1.        , 0.12      , 1.        , 0.09090909, 0.92857143,
       0.12      , 1.        , 0.18604651, 0.04      , 0.        ,
       1.        , 0.12      , 1.        , 1.        , 0.        ,
       1.        , 0.13043478, 1.        , 0.12      , 0.        ,
       1.        , 0.04      , 0.12      , 1.        , 1.        ,
       1.        , 0.13043478, 0.85      , 0.        , 0.18604651,
       1.        , 0.18604651, 0.12      , 0.        , 0.        ,
       1.        , 0.        , 0.92857143, 0.92857143, 1.        ,
       0.92857143, 1.        , 0.        , 0.18604651, 0.04      ,
       0.12      , 1.        , 1.        , 0.18604651, 0.        ,
       1.        , 1.        , 0.        , 0.13043478, 1.        ,
       1.        , 0.        , 1.        , 1.        , 0.        ,
       1.        , 0.        , 0.09090909, 0.        , 1.        ,
       1.        , 0.18604651, 0.        , 1.        , 0.04   

In [43]:
new['pred'] = tree.predict(new.loc[:,'age':'mortgage'])
new.head()

id  age  sex  region    income  married  children  car  save_act  \
0  ID12701   23    1       0  18766.90        1         0    1         1   
1  ID12702   30    1       1   9915.67        0         1    0         1   
2  ID12703   45    0       1  21881.60        0         0    1         1   
3  ID12704   50    1       3  46794.40        1         2    0         1   
4  ID12705   41    0       0  20721.10        1         0    1         1   

   current_act  mortgage  pred  
0            0         1     0  
1            0         1     0  
2            1         0     1  
3            0         1     1  
4            1         0     0

In [58]:
# 개인연금 구매확률을 예측
new['pred_prob'] = tree.predict_proba(new.loc[:,'age':'mortgage'])[:,1]
new.head()

id  age  sex  region    income  married  children  car  save_act  \
0  ID12701   23    1       0  18766.90        1         0    1         1   
1  ID12702   30    1       1   9915.67        0         1    0         1   
2  ID12703   45    0       1  21881.60        0         0    1         1   
3  ID12704   50    1       3  46794.40        1         2    0         1   
4  ID12705   41    0       0  20721.10        1         0    1         1   

   current_act  mortgage  pred  pred_prob  
0            0         1     0   0.120000  
1            0         1     0   0.000000  
2            1         0     1   1.000000  
3            0         1     1   1.000000  
4            1         0     0   0.186047

In [72]:
# PEP에 가입할 확율이 70%가 넘는 고객만 추출
target = new.query('pred == 1 & pred_prob > 0.7')
target.sort_values(by="pred_prob", ascending=False).to_csv("pep_target_조성혁.csv", index=False)
pd.read_csv("pep_target_조성혁.csv").head()

id  age  sex  region   income  married  children  car  save_act  \
0  ID12703   45    0       1  21881.6        0         0    1         1   
1  ID12830   46    0       0  17049.3        0         1    0         1   
2  ID12782   44    1       1  39202.2        0         1    1         1   
3  ID12784   37    1       2  17629.3        1         1    0         1   
4  ID12704   50    1       3  46794.4        1         2    0         1   

   current_act  mortgage  pred  pred_prob  
0            1         0     1        1.0  
1            0         0     1        1.0  
2            1         1     1        1.0  
3            1         1     1        1.0  
4            0         1     1        1.0