# NumPy

## 리스트 
 - 여러개의요소를담는가변적인표준컨테이너
 - 서로 다른 데이터 타입의 요소를 담는 리스트 생성 가능
 - 단점: 행렬연산등 처리의 어려움

In [6]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(L[0])

int

In [6]:
L2 = [True, '2', 3.0, 4]
L2

[True, '2', 3.0, 4]

In [13]:
[type(item) for item in L2]

[bool, str, float, int]

In [10]:
for item in L2:
    print(type(item))

<class 'bool'>
<class 'str'>
<class 'float'>
<class 'int'>


### NumPy 패키지를 사용하여 행렬 연산 및 처리가 가능한 배열(Array) 생성
 - NumPy는 배열의 모든 요소가 같은 타입
 - 타입이 일치하지 않으면 NumPy는 가능한 경우 상위타입을 취함
 - dypte키워드를 사용하여 데이터 타입 설정도 가능
 - 리스트의 중첩을 통해 다차원배열 생성 가능

In [15]:
import numpy as np

In [12]:
np.array([1,4,5,3])

array([1, 4, 5, 3])

In [20]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [26]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [29]:
np.array([[2,3,4],[5,6,7],[8,9,'10']])

array([['2', '3', '4'],
       ['5', '6', '7'],
       ['8', '9', '10']], dtype='<U21')

In [63]:
# 0으로 채운 길이 10의 정수 배열  # dtype default value = float
display(np.zeros((2,2,10), dtype=int))
display(np.zeros((3,10), dtype=float))
display(np.zeros(10, dtype=str))

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

array(['', '', '', '', '', '', '', '', '', ''], dtype='<U1')

In [54]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
# 1로 채운 3*5 배열  # dtype default value = float
np.ones((3,5), dtype=int)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
# 지정한 값으로 채운 3*5 배열 두개  # dtype default value = float
np.full((2,3,5), 3.14)

array([[[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]],

       [[3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14],
        [3.14, 3.14, 3.14, 3.14, 3.14]]])

In [60]:
np.full((2,3,5), 3.14, dtype='int')

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [96]:
arange = np.arange(0,21,2)

arange[0] = 1  # 인덱싱 가능
print(arange)
arange1 = arange[:3]
print(arange1)
arange2 = arange[::2]
print(arange2)
arange3 = arange.sort()
print(sorted(arange,reverse=True))  # sort() 불가

#arange.remove(1)  # remove() 불가
#arange.index(2)  # index() 불가
#arange.append(10)  # append() 불가
#arange.insert(0,3)  # insert() 불가
#del arange[0]  # del 로 삭제 불가
#arange.clear()  # clear() 불가
#arange.sort()  # sort() none 값 출력


[ 1  2  4  6  8 10 12 14 16 18 20]
[1 2 4]
[ 1  4  8 12 16 20]
[20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 1]


In [106]:
# 0과 1 사이에 일정한 간격을 지닌 다섯개의 값
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [100]:
np.random.random((10))

array([0.92982107, 0.69258192, 0.99224974, 0.66964819, 0.52124871,
       0.03781613, 0.58604924, 0.93772683, 0.15636935, 0.25959032])

In [98]:
# 0과 1사이의 난수로 구성된 3*3 배열
np.random.random((3,3))

array([[0.45577597, 0.67115972, 0.43186179],
       [0.13919063, 0.69621064, 0.47517918],
       [0.15793074, 0.1385353 , 0.45066893]])

In [107]:
# 정규분포(평균=0, 표준편차=1)의 난수로 구성된 3*3 배열
np.random.normal(0,1,(3,3))

array([[ 0.64687085,  1.78030889, -0.45322264],
       [ 0.33000913, -1.71652652, -0.04264973],
       [ 0.13255442, -0.21187376,  1.04890897]])

In [25]:
# 0과 10 사이의 정수 난수로 구성된 3*3배열
np.random.randint(0, 11, (3,3))

array([[1, 7, 4],
       [3, 4, 6],
       [4, 3, 0]])

### NumPy 내장 루틴 : 사전 정의된 배열 사용

In [119]:
# 3*3 단위 행렬
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [127]:
# 3개의 정수를 가지는 초기화되지 않은 배열 만들기
np.empty(10)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [28]:
# NumPy 데이터 타입
# bool : 1바이트로 저장된 bool 값 (참 또는 거짓)
# int : int64 또는 int32
# Int8 : 바이트(-128~127)
# int16 : 정수(-32768~32767)
# int32 : 정수(-2147483648~2147483647)
# int64 : 정수(-9223372036854775808~9223372036854775807)
# unit8 : 부호없는정수(0~255)
# unit16 : 부호없는정수(0~65535)
# unit32 : 부호없는정수(0~4294967295)
# unit64 : 부호없는정수(0~18446744073709551615)
# float : float64
# float16 : 반정밀부동소수점,5비트지수,10비트가수
# float32 : 단정밀부동소수점,8비트지수,32비트가수
# float64 : 배정밀부동소수점,11비트지수,53비트가수
# complex : complex128
# complex64 : 복소수,두개의32비트부동소수점으로표현
# complex128 : 복소수,두개의64비트부동소수점으로표현

In [132]:
np.random.seed(123)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[4, 1, 7, 3, 2],
        [4, 7, 2, 4, 8],
        [0, 7, 9, 3, 4],
        [6, 1, 5, 6, 2]],

       [[1, 8, 3, 5, 0],
        [2, 6, 2, 4, 4],
        [6, 3, 0, 6, 4],
        [7, 6, 7, 1, 5]],

       [[7, 9, 2, 4, 8],
        [1, 2, 1, 1, 3],
        [5, 9, 0, 8, 1],
        [6, 3, 3, 5, 9]]])

In [30]:
# 배열 속성 지정
print(x3.ndim) # 차원의 개수
print(x3.shape) # 각 차원의 크기
print(x3.size) # 전체 배열의 크기
print(x3.dtype) # 데이터 타입
print(x3.itemsize) # 배열 요소의 크기(바이트 단위)
print(x3.nbytes) # 배열의 전체 크기(바이트 단위)

3
(3, 4, 5)
60
int64
8
480


In [31]:
x1

array([2, 2, 6, 1, 3, 9])

In [32]:
print(x1[0])
print(x1[-1])

2
9


In [33]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [34]:
print(x2[0,0])
print(x2[1,-1])

6
9


In [35]:
# 배열 슬라이싱
x = np.arange(10)
print(x)
print(x[5:])
print(x[4:7])
print(x[0:2])
print(x[::2])
print(x[1::2])
print(x[::-1])
print(x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[4 5 6]
[0 1]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [36]:
x2

array([[6, 1, 0, 1],
       [9, 0, 0, 9],
       [3, 4, 0, 0]])

In [37]:
x2[:2, :3]

array([[6, 1, 0],
       [9, 0, 0]])

In [38]:
x2[:,0]

array([6, 9, 3])

In [39]:
x2_sub = x2[:2, :2]
x2_sub

array([[6, 1],
       [9, 0]])

In [40]:
x2_sub[0,0]=99
x2_sub

array([[99,  1],
       [ 9,  0]])

In [41]:
x2

array([[99,  1,  0,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

In [42]:
x2_sub = x2[:2, :2].copy()
x2_sub

array([[99,  1],
       [ 9,  0]])

In [43]:
x2_sub[0,0]=42
x2_sub

array([[42,  1],
       [ 9,  0]])

In [44]:
x2

array([[99,  1,  0,  1],
       [ 9,  0,  0,  9],
       [ 3,  4,  0,  0]])

### 배열 재구조화(형상 변경)
 - reshape() 메소드를 사용
 - 1차원 배열을 2차원 행이나 열 매트릭스로 전환하는 경우에는 슬라이스 연산 내에 newaxis 키워드 사용

In [2]:
import numpy as np
grid = np.arange(1,10)
x = np.array([1,2,3,4,5,6,7,8,9])
print(grid)
print(x)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [11]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [8]:
x[:, np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [48]:
# 배열 결합
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [49]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [50]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
# 첫번째 축을 따라 연결
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [51]:
# 두번째 축을 따라 연결
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [52]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
# 수직 쌓기
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [53]:
y = np.array([[99],[99]])
# 수평 쌓기
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [156]:
# 하나의 배열을 여러 개로 분할
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [157]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [167]:
upper, lower = np.vsplit(grid, [1])
print(upper)
print(lower)

[[0 1 2 3]]
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [57]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 1. 출력 지정

In [179]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
y

array([ 0., 10., 20., 30., 40.])

In [172]:
y = np.zeros(10)
np.power(2, x, out = y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [184]:
## 1. 출력 지정

x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

y = np.zeros(10)
np.power(2, x, out = y[::2])

[ 0. 10. 20. 30. 40.]


array([ 1.,  2.,  4.,  8., 16.])

## 2. 집계

In [61]:
x = np.arange(1,10)
np.add.reduce(x)

45

In [62]:
np.multiply.reduce(x)

362880

In [63]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [64]:
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

# Pandas Basics

## 1. 데이터 프레임의 이해

In [65]:
import pandas as pd

In [66]:
movie = pd.read_csv('data/movie.csv')
movie.head()

color      director_name  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [67]:
index = movie.index
index

RangeIndex(start=0, stop=4916, step=1)

In [68]:
columns = movie.columns
columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [69]:
data = movie.values
type(data)

numpy.ndarray

In [70]:
index.values

array([   0,    1,    2, ..., 4913, 4914, 4915])

In [71]:
columns.values

array(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes',
       'actor_2_name', 'actor_1_facebook_likes', 'gross', 'genres',
       'actor_1_name', 'movie_title', 'num_voted_users',
       'cast_total_facebook_likes', 'actor_3_name',
       'facenumber_in_poster', 'plot_keywords', 'movie_imdb_link',
       'num_user_for_reviews', 'language', 'country', 'content_rating',
       'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score',
       'aspect_ratio', 'movie_facebook_likes'], dtype=object)

In [72]:
movie.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
m

In [74]:
movie.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   color                      4897 non-null   object 
 1   director_name              4814 non-null   object 
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   object 
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   object 
 10  actor_1_name               4909 non-null   object 
 11  movie_title                4916 non-null   object 
 12  num_voted_users            4916 non-null   int64  
 13  cast_total_facebook_likes  4916 non-null   int64

## 2. Series

### 2.1. Series 생성

In [75]:
movie['director_name']

0           James Cameron
1          Gore Verbinski
2              Sam Mendes
3       Christopher Nolan
4             Doug Walker
              ...        
4911          Scott Smith
4912                  NaN
4913     Benjamin Roberds
4914          Daniel Hsia
4915             Jon Gunn
Name: director_name, Length: 4916, dtype: object

### 2.2. Series 메서드

In [76]:
# Series 메서드
"""
head() : 데이터일부를표시
value_counts() : 고유값의빈도수계산(Series만지원) / normalize=True로설정하면상대빈도
size, shape, len(x) : 원소개수계산
count():결측치를제외한개수
min(), max(), mean(), median(), std(), sum()
describe() : 요약통계량제공(개수, 평균, 표준편차, 최소값, 4분위수, 최대값)
quantile() : 정확한분위수계산
isnull():결측치체크<-> notnull()
fillna() : 결측치를한번에특정값으로변환
dropna() : 결측치제거
hasnans: 하나라도결측치가있으면True (Series만지원)
astype() : 데이터형식변경(결측치가있는경우오류)
"""

'\nhead() : 데이터일부를표시\nvalue_counts() : 고유값의빈도수계산(Series만지원) / normalize=True로설정하면상대빈도\uf0a7\nsize, shape, len(x) : 원소개수계산\uf0a7\ncount():결측치를제외한개수\nmin(), max(), mean(), median(), std(), sum()\ndescribe() : 요약통계량제공(개수, 평균, 표준편차, 최소값, 4분위수, 최대값)\nquantile() : 정확한분위수계산\nisnull():결측치체크<-> notnull()\nfillna() : 결측치를한번에특정값으로변환\ndropna() : 결측치제거\nhasnans: 하나라도결측치가있으면True (Series만지원)\nastype() : 데이터형식변경(결측치가있는경우오류)\n'

In [77]:
director = movie['director_name']
director.head()

0        James Cameron
1       Gore Verbinski
2           Sam Mendes
3    Christopher Nolan
4          Doug Walker
Name: director_name, dtype: object

In [78]:
score = movie['imdb_score']
score.head()

0    7.9
1    7.1
2    6.8
3    8.5
4    7.1
Name: imdb_score, dtype: float64

In [79]:
# 가장 유용한 메서드, 
director.value_counts()

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
                    ..
Dick Richards        1
Norman Ferguson      1
Lucrecia Martel      1
Stefan Schwartz      1
Don Siegel           1
Name: director_name, Length: 2397, dtype: int64

In [80]:
# normalize=True 모든 값을 값의 합으로 나누어 상대 빈도를 반환
director.value_counts(normalize=True)

Steven Spielberg    0.005401
Woody Allen         0.004570
Martin Scorsese     0.004155
Clint Eastwood      0.004155
Ridley Scott        0.003324
                      ...   
Dick Richards       0.000208
Norman Ferguson     0.000208
Lucrecia Martel     0.000208
Stefan Schwartz     0.000208
Don Siegel          0.000208
Name: director_name, Length: 2397, dtype: float64

In [81]:
director.size

4916

In [82]:
director.shape

(4916,)

In [83]:
len(director)

4916

In [84]:
director.count()

4814

In [85]:
score.describe()

count    4916.000000
mean        6.437429
std         1.127802
min         1.600000
25%         5.800000
50%         6.600000
75%         7.200000
max         9.500000
Name: imdb_score, dtype: float64

In [86]:
# 분위수
score.quantile(0.2)

5.6

In [87]:
s = pd.Series([1, 2, 3, 4])
s.quantile(.5)

2.5

In [88]:
s.quantile([.25, .5, .75])

0.25    1.75
0.50    2.50
0.75    3.25
dtype: float64

In [89]:
director.isnull()

0       False
1       False
2       False
3       False
4       False
        ...  
4911    False
4912     True
4913    False
4914    False
4915    False
Name: director_name, Length: 4916, dtype: bool

In [90]:
director.isnull().sum()

102

In [91]:
director_fill = director.fillna('Unknown')
print(director.count(), director_fill.count())

4814 4916


In [92]:
director_drop = director.dropna()
print(director.size, director_drop.size)

4916 4814


In [93]:
director.hasnans # Nan 파악

True

In [94]:
score.astype(int)

0       7
1       7
2       6
3       8
4       7
       ..
4911    7
4912    7
4913    6
4914    6
4915    6
Name: imdb_score, Length: 4916, dtype: int64

### 2.3. 메서드 체인

In [95]:
director.value_counts().head()

Steven Spielberg    26
Woody Allen         22
Martin Scorsese     20
Clint Eastwood      20
Ridley Scott        16
Name: director_name, dtype: int64

In [96]:
score.fillna(0).astype(int).head()

0    7
1    7
2    6
3    8
4    7
Name: imdb_score, dtype: int64

## 3. 열과 행 다루기

In [97]:
# movie_title열을 인덱스로 설정할 수 있다. 이 때 기존 인덱스는 없어진다.
movie2 = movie.set_index('movie_title')
movie2

color      director_name  \
movie_title                                                            
Avatar                                      Color      James Cameron   
Pirates of the Caribbean: At World's End    Color     Gore Verbinski   
Spectre                                     Color         Sam Mendes   
The Dark Knight Rises                       Color  Christopher Nolan   
Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker   
...                                           ...                ...   
Signed Sealed Delivered                     Color        Scott Smith   
The Following                               Color                NaN   
A Plague So Pleasant                        Color   Benjamin Roberds   
Shanghai Calling                            Color        Daniel Hsia   
My Date with Drew                           Color           Jon Gunn   

                                            num_critic_for_reviews  duration  \
movie_title                                                                    
Avatar                                                       723.0     178.0   
Pirates of the Caribbean: At World's End                     302.0     169.0   
Spectre                                                      602.0     148.0   
The Dark Knight Rises                                        813.0     164.0   
Star Wars: Episode VII - The Force Awakens                     NaN       NaN   
...                                                            ...       ...   
Signed Sealed Delivered                                        1.0      87.0   
The Following                                                 43.0      43.0   
A Plague So Pleasant                                          13.0      76.0   
Shanghai Calling                                              14.0     100.0   
My Date with Drew                                             43.0      90.0   

                                            director_facebook_likes  \
movie_title                                                           
Avatar                                                          0.0   
Pirates of the Caribbean: At World's End                      563.0   
Spectre                                                         0.0   
The Dark Knight Rises                                       22000.0   
Star Wars: Episode VII - The Force Awakens                    131.0   
...                                                             ...   
Signed Sealed Delivered                                         2.0   
The Following                                                   NaN   
A Plague So Pleasant                                            0.0   
Shanghai Calling                                                0.0   
My Date with Drew                                              16.0   

                                            actor_3_facebook_likes  \
movie_title                                                          
Avatar                                                       855.0   
Pirates of the Caribbean: At World's End                    1000.0   
Spectre                                                      161.0   
The Dark Knight Rises                                      23000.0   
Star Wars: Episode VII - The Force Awakens                     NaN   
...                                                            ...   
Signed Sealed Delivered                                      318.0   
The Following                                                319.0   
A Plague So Pleasant                                           0.0   
Shanghai Calling                                             489.0   
My Date with Drew                                             16.0   

                                                actor_2_name  \
movie_title                                                    
Avatar                                      Joel David Moore   
Pirates of the Caribbean: At World's En

In [98]:
movie2 = pd.read_csv('data/movie.csv', index_col='movie_title')
movie2.head()

color      director_name  \
movie_title                                                            
Avatar                                      Color      James Cameron   
Pirates of the Caribbean: At World's End    Color     Gore Verbinski   
Spectre                                     Color         Sam Mendes   
The Dark Knight Rises                       Color  Christopher Nolan   
Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker   

                                            num_critic_for_reviews  duration  \
movie_title                                                                    
Avatar                                                       723.0     178.0   
Pirates of the Caribbean: At World's End                     302.0     169.0   
Spectre                                                      602.0     148.0   
The Dark Knight Rises                                        813.0     164.0   
Star Wars: Episode VII - The Force Awakens                     NaN       NaN   

                                            director_facebook_likes  \
movie_title                                                           
Avatar                                                          0.0   
Pirates of the Caribbean: At World's End                      563.0   
Spectre                                                         0.0   
The Dark Knight Rises                                       22000.0   
Star Wars: Episode VII - The Force Awakens                    131.0   

                                            actor_3_facebook_likes  \
movie_title                                                          
Avatar                                                       855.0   
Pirates of the Caribbean: At World's End                    1000.0   
Spectre                                                      161.0   
The Dark Knight Rises                                      23000.0   
Star Wars: Episode VII - The Force Awakens                     NaN   

                                                actor_2_name  \
movie_title                                                    
Avatar                                      Joel David Moore   
Pirates of the Caribbean: At World's End       Orlando Bloom   
Spectre                                         Rory Kinnear   
The Dark Knight Rises                         Christian Bale   
Star Wars: Episode VII - The Force Awakens        Rob Walker   

                                            actor_1_facebook_likes  \
movie_title                                                          
Avatar                                                      1000.0   
Pirates of the Caribbean: At World's End                   40000.0   
Spectre                                                    11000.0   
The Dark Knight Rises                                      27000.0   
Star Wars: Episode VII - The Force Awakens                   131.0   

                                                  gross  \
movie_title                                               
Avatar                                      760505847.0   
Pirates of the Caribbean: At World's End    309404152.0   
Spectre                                     200074175.0   
The Dark Knight Rises                       448130642.0   
Star Wars: Episode VII - The Force Awakens          NaN   

                                                                     genres  \
movie_title                                                                   
Avatar                                      Action|Adventure|Fantasy|Sci-Fi   
Pirates of the Caribbean: At World's End           Action|Adventure|Fantasy   
Spectre                                           Action|Adventure|Thriller   
The Dark Knight Rises                                       Action|Thriller   
Star Wars: Episode VII - The Force Awakens                      Documentary   

                                            ... num_user_for_reviews  \
movie_tit

In [99]:
"""
reset_index 명령으로 인덱스를 보통의 자료열로 바꿀 수도 있다. 
이 때 인덱스 열은 자료열의 가장 선두로 삽입된다. 
데이터프레임의 인덱스는 정수로 된 디폴트 인덱스로 바뀐다.
"""
movie2 = movie2.reset_index()
movie2

movie_title  color      director_name  \
0                                         Avatar  Color      James Cameron   
1       Pirates of the Caribbean: At World's End  Color     Gore Verbinski   
2                                        Spectre  Color         Sam Mendes   
3                          The Dark Knight Rises  Color  Christopher Nolan   
4     Star Wars: Episode VII - The Force Awakens    NaN        Doug Walker   
...                                          ...    ...                ...   
4911                     Signed Sealed Delivered  Color        Scott Smith   
4912                               The Following  Color                NaN   
4913                        A Plague So Pleasant  Color   Benjamin Roberds   
4914                            Shanghai Calling  Color        Daniel Hsia   
4915                           My Date with Drew  Color           Jon Gunn   

      num_critic_for_reviews  duration  director_facebook_likes  \
0                      723.0     178.0                      0.0   
1                      302.0     169.0                    563.0   
2                      602.0     148.0                      0.0   
3                      813.0     164.0                  22000.0   
4                        NaN       NaN                    131.0   
...                      ...       ...                      ...   
4911                     1.0      87.0                      2.0   
4912                    43.0      43.0                      NaN   
4913                    13.0      76.0                      0.0   
4914                    14.0     100.0                      0.0   
4915                    43.0      90.0                     16.0   

      actor_3_facebook_likes      actor_2_name  actor_1_facebook_likes  \
0                      855.0  Joel David Moore                  1000.0   
1                     1000.0     Orlando Bloom                 40000.0   
2                      161.0      Rory Kinnear                 11000.0   
3                    23000.0    Christian Bale                 27000.0   
4                        NaN        Rob Walker                   131.0   
...                      ...               ...                     ...   
4911                   318.0     Daphne Zuniga                   637.0   
4912                   319.0     Valorie Curry                   841.0   
4913                     0.0     Maxwell Moody                     0.0   
4914                   489.0     Daniel Henney                   946.0   
4915                    16.0  Brian Herzlinger                    86.0   

            gross  ... num_user_for_reviews language  country  content_rating  \
0     760505847.0  ...               3054.0  English      USA           PG-13   
1     309404152.0  ...               1238.0  English      USA           PG-13   
2     200074175.0  ...                994.0  English       UK           PG-13   
3     448130642.0  ...               2701.0  English      USA           PG-13   
4             NaN  ...                  NaN      NaN      NaN             NaN   
...           ...  ...                  ...      ...      ...             ...   
4911          NaN  ...                  6.0  English   Canada             NaN   
4912          NaN  ...                359.0  English      USA           TV-14   
4913          NaN  ...                  3.0  English      USA             NaN   
4914      10443.0  ...                  9.0  English      USA           PG-13   
4915      85222.0  ...                 84.0  English      USA              PG   

           budget  title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0     237000000.0      2009.0                  936.0        7.9          1.78   
1     300000000.0      2007.0                 5000.0        7.1          2.35   
2     245000000.0      2015.0                  393.0        6.8          2.35   
3     250000000.0      2012.0                23000.0        8.5          2.35   
4             NaN         Na

In [100]:
movie_rename = movie.rename(index={0:'아바타'}, columns={'color':'색깔','director_name':'감독이름'})
movie_rename

색깔               감독이름  num_critic_for_reviews  duration  \
아바타   Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
아바타                       0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
아바타                   1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... num_user_for_reviews language  country  content_rating       budget  \
아바타   ...               3054.0  English      USA           PG-13  237000000.0   
1     ...               1238.0  English      USA           PG-13  300000000.0   
2     ...                994.0  English       UK           PG-13  245000000.0   
3     ...               2701.0  English      USA           PG-13  250000000.0   
4     ...                  NaN      NaN      NaN             NaN          NaN   
...   ...                  ...      ...      ...             ...          ...   
4911  ...                  6.0  English   Canada             NaN          NaN   
4912  ...                359.0  English      USA           TV-14          NaN   
4913  ...                  3.0  English      USA             NaN       1400.0   
4914  ...                  9.0  English      USA           PG-13          NaN   
4915  ...                 84.0  English      USA              PG       1100.0   

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
아바타       2009.0                  936.0        7.9          1.78   
1         2007.0                 5000.0        7.1          2.35   
2         2015.0                  393.0        6.8          2.35   
3         2012.0                23000.0        8.5          2.35   
4            NaN                   12.0  

In [101]:
# 컬럼을 리스트로 생성
col = movie.columns
col_list = col.tolist()
col_list

['color',
 'director_name',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

In [102]:
col_list[0]='색깔'
col_list[1]='감독이름'
col_list

['색깔',
 '감독이름',
 'num_critic_for_reviews',
 'duration',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'aspect_ratio',
 'movie_facebook_likes']

In [103]:
movie.columns = col_list
movie.head()

색깔               감독이름  num_critic_for_reviews  duration  \
0  Color      James Cameron                   723.0     178.0   
1  Color     Gore Verbinski                   302.0     169.0   
2  Color         Sam Mendes                   602.0     148.0   
3  Color  Christopher Nolan                   813.0     164.0   
4    NaN        Doug Walker                     NaN       NaN   

   director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                      0.0                   855.0  Joel David Moore   
1                    563.0                  1000.0     Orlando Bloom   
2                      0.0                   161.0      Rory Kinnear   
3                  22000.0                 23000.0    Christian Bale   
4                    131.0                     NaN        Rob Walker   

   actor_1_facebook_likes        gross                           genres  ...  \
0                  1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi  ...   
1                 40000.0  309404152.0         Action|Adventure|Fantasy  ...   
2                 11000.0  200074175.0        Action|Adventure|Thriller  ...   
3                 27000.0  448130642.0                  Action|Thriller  ...   
4                   131.0          NaN                      Documentary  ...   

  num_user_for_reviews language  country  content_rating       budget  \
0               3054.0  English      USA           PG-13  237000000.0   
1               1238.0  English      USA           PG-13  300000000.0   
2                994.0  English       UK           PG-13  245000000.0   
3               2701.0  English      USA           PG-13  250000000.0   
4                  NaN      NaN      NaN             NaN          NaN   

   title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
0      2009.0                  936.0        7.9          1.78   
1      2007.0                 5000.0        7.1          2.35   
2      2015.0                  393.0        6.8          2.35   
3      2012.0                23000.0        8.5          2.35   
4         NaN                   12.0        7.1           NaN   

  movie_facebook_likes  
0                33000  
1                    0  
2                85000  
3               164000  
4                    0  

[5 rows x 28 columns]

In [104]:
movie.drop(range(10), axis='index')

색깔              감독이름  num_critic_for_reviews  duration  \
10    Color       Zack Snyder                   673.0     183.0   
11    Color      Bryan Singer                   434.0     169.0   
12    Color      Marc Forster                   403.0     106.0   
13    Color    Gore Verbinski                   313.0     151.0   
14    Color    Gore Verbinski                   450.0     150.0   
...     ...               ...                     ...       ...   
4911  Color       Scott Smith                     1.0      87.0   
4912  Color               NaN                    43.0      43.0   
4913  Color  Benjamin Roberds                    13.0      76.0   
4914  Color       Daniel Hsia                    14.0     100.0   
4915  Color          Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
10                        0.0                  2000.0      Lauren Cohan   
11                        0.0                   903.0     Marlon Brando   
12                      395.0                   393.0   Mathieu Amalric   
13                      563.0                  1000.0     Orlando Bloom   
14                      563.0                  1000.0       Ruth Wilson   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                        genres  ...  \
10                   15000.0  330249062.0       Action|Adventure|Sci-Fi  ...   
11                   18000.0  200069408.0       Action|Adventure|Sci-Fi  ...   
12                     451.0  168368427.0              Action|Adventure  ...   
13                   40000.0  423032628.0      Action|Adventure|Fantasy  ...   
14                   40000.0   89289910.0      Action|Adventure|Western  ...   
...                      ...          ...                           ...  ...   
4911                   637.0          NaN                  Comedy|Drama  ...   
4912                   841.0          NaN  Crime|Drama|Mystery|Thriller  ...   
4913                     0.0          NaN         Drama|Horror|Thriller  ...   
4914                   946.0      10443.0          Comedy|Drama|Romance  ...   
4915                    86.0      85222.0                   Documentary  ...   

     num_user_for_reviews language  country  content_rating       budget  \
10                 3018.0  English      USA           PG-13  250000000.0   
11                 2367.0  English      USA           PG-13  209000000.0   
12                 1243.0  English       UK           PG-13  200000000.0   
13                 1832.0  English      USA           PG-13  225000000.0   
14                  711.0  English      USA           PG-13  215000000.0   
...                   ...      ...      ...             ...          ...   
4911                  6.0  English   Canada             NaN          NaN   
4912                359.0  English      USA           TV-14          NaN   
4913                  3.0  English      USA             NaN       1400.0   
4914                  9.0  English      USA           PG-13          NaN   
4915                 84.0  English      USA              PG       1100.0   

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
10        2016.0                 4000.0        6.9          2.35   
11        2006.0                10000.0        6.1          2.35   
12        2008.0                  412.0        6.7          2.35   
13        2006.0                 5000.0        7.3          2.35   
14        2013.0                 2000.0        6.5          2.35   
...          ...     

In [105]:
movie.drop(['색깔','감독이름'], axis='columns')

num_critic_for_reviews  duration  director_facebook_likes  \
0                      723.0     178.0                      0.0   
1                      302.0     169.0                    563.0   
2                      602.0     148.0                      0.0   
3                      813.0     164.0                  22000.0   
4                        NaN       NaN                    131.0   
...                      ...       ...                      ...   
4911                     1.0      87.0                      2.0   
4912                    43.0      43.0                      NaN   
4913                    13.0      76.0                      0.0   
4914                    14.0     100.0                      0.0   
4915                    43.0      90.0                     16.0   

      actor_3_facebook_likes      actor_2_name  actor_1_facebook_likes  \
0                      855.0  Joel David Moore                  1000.0   
1                     1000.0     Orlando Bloom                 40000.0   
2                      161.0      Rory Kinnear                 11000.0   
3                    23000.0    Christian Bale                 27000.0   
4                        NaN        Rob Walker                   131.0   
...                      ...               ...                     ...   
4911                   318.0     Daphne Zuniga                   637.0   
4912                   319.0     Valorie Curry                   841.0   
4913                     0.0     Maxwell Moody                     0.0   
4914                   489.0     Daniel Henney                   946.0   
4915                    16.0  Brian Herzlinger                    86.0   

            gross                           genres     actor_1_name  \
0     760505847.0  Action|Adventure|Fantasy|Sci-Fi      CCH Pounder   
1     309404152.0         Action|Adventure|Fantasy      Johnny Depp   
2     200074175.0        Action|Adventure|Thriller  Christoph Waltz   
3     448130642.0                  Action|Thriller        Tom Hardy   
4             NaN                      Documentary      Doug Walker   
...           ...                              ...              ...   
4911          NaN                     Comedy|Drama      Eric Mabius   
4912          NaN     Crime|Drama|Mystery|Thriller      Natalie Zea   
4913          NaN            Drama|Horror|Thriller      Eva Boehnke   
4914      10443.0             Comedy|Drama|Romance        Alan Ruck   
4915      85222.0                      Documentary      John August   

                                     movie_title  ...  num_user_for_reviews  \
0                                         Avatar  ...                3054.0   
1       Pirates of the Caribbean: At World's End  ...                1238.0   
2                                        Spectre  ...                 994.0   
3                          The Dark Knight Rises  ...                2701.0   
4     Star Wars: Episode VII - The Force Awakens  ...                   NaN   
...                                          ...  ...                   ...   
4911                     Signed Sealed Delivered  ...                   6.0   
4912                               The Following  ...                 359.0   
4913                        A Plague So Pleasant  ...                   3.0   
4914                            Shanghai Calling  ...                   9.0   
4915                           My Date with Drew  ...                  84.0   

      language country  content_rating       budget title_year  \
0      English     USA           PG-13  237000000.0     2009.0   
1      English     USA           PG-13  300000000.0     2007.0   
2      English      UK           PG-13  245000000.0     2015.0   
3      English     USA           PG-13  250000000.0     2012.0   
4          NaN     NaN             NaN          NaN        NaN   
...        ...     ...             ...          ...        ...   
4911   English  Canada             NaN          

In [106]:
movie['has_seen'] = 0
movie

색깔               감독이름  num_critic_for_reviews  duration  \
0     Color      James Cameron                   723.0     178.0   
1     Color     Gore Verbinski                   302.0     169.0   
2     Color         Sam Mendes                   602.0     148.0   
3     Color  Christopher Nolan                   813.0     164.0   
4       NaN        Doug Walker                     NaN       NaN   
...     ...                ...                     ...       ...   
4911  Color        Scott Smith                     1.0      87.0   
4912  Color                NaN                    43.0      43.0   
4913  Color   Benjamin Roberds                    13.0      76.0   
4914  Color        Daniel Hsia                    14.0     100.0   
4915  Color           Jon Gunn                    43.0      90.0   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross                           genres  \
0                     1000.0  760505847.0  Action|Adventure|Fantasy|Sci-Fi   
1                    40000.0  309404152.0         Action|Adventure|Fantasy   
2                    11000.0  200074175.0        Action|Adventure|Thriller   
3                    27000.0  448130642.0                  Action|Thriller   
4                      131.0          NaN                      Documentary   
...                      ...          ...                              ...   
4911                   637.0          NaN                     Comedy|Drama   
4912                   841.0          NaN     Crime|Drama|Mystery|Thriller   
4913                     0.0          NaN            Drama|Horror|Thriller   
4914                   946.0      10443.0             Comedy|Drama|Romance   
4915                    86.0      85222.0                      Documentary   

      ... language country  content_rating       budget title_year  \
0     ...  English     USA           PG-13  237000000.0     2009.0   
1     ...  English     USA           PG-13  300000000.0     2007.0   
2     ...  English      UK           PG-13  245000000.0     2015.0   
3     ...  English     USA           PG-13  250000000.0     2012.0   
4     ...      NaN     NaN             NaN          NaN        NaN   
...   ...      ...     ...             ...          ...        ...   
4911  ...  English  Canada             NaN          NaN     2013.0   
4912  ...  English     USA           TV-14          NaN        NaN   
4913  ...  English     USA             NaN       1400.0     2013.0   
4914  ...  English     USA           PG-13          NaN     2012.0   
4915  ...  English     USA              PG       1100.0     2004.0   

      actor_2_facebook_likes imdb_score aspect_ratio  movie_facebook_likes  \
0                      936.0        7.9         1.78                 33000   
1                     5000.0        7.1         2.35                     0   
2                      393.0        6.8         2.35                 85000   
3                    23000.0        8.5         2.35                164000   
4                       12.0        7.1          NaN                     0   
...                      ...        ...      

In [107]:
# 컬럼위치
avg_index = movie.columns.get_loc('duration') + 1
avg_index

4

In [108]:
"""
DataFrameName.insert (loc, column, value, allow_duplicates = False)
loc : loc은 새로운 열을 삽입하고자하는 열의 위치 인 정수. 
      해당 위치의 기존 열이 오른쪽으로 이동.
column : column은 삽입 할 열의 이름 인 문자열. 
value : 삽입 할 값
allow_duplicates :동일한 이름의 열이 존재하는지 여부 확인.
"""
movie.insert(loc=avg_index, column='평균리뷰수', value=movie['num_critic_for_reviews']/movie['duration'])
movie

색깔               감독이름  num_critic_for_reviews  duration     평균리뷰수  \
0     Color      James Cameron                   723.0     178.0  4.061798   
1     Color     Gore Verbinski                   302.0     169.0  1.786982   
2     Color         Sam Mendes                   602.0     148.0  4.067568   
3     Color  Christopher Nolan                   813.0     164.0  4.957317   
4       NaN        Doug Walker                     NaN       NaN       NaN   
...     ...                ...                     ...       ...       ...   
4911  Color        Scott Smith                     1.0      87.0  0.011494   
4912  Color                NaN                    43.0      43.0  1.000000   
4913  Color   Benjamin Roberds                    13.0      76.0  0.171053   
4914  Color        Daniel Hsia                    14.0     100.0  0.140000   
4915  Color           Jon Gunn                    43.0      90.0  0.477778   

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
0                         0.0                   855.0  Joel David Moore   
1                       563.0                  1000.0     Orlando Bloom   
2                         0.0                   161.0      Rory Kinnear   
3                     22000.0                 23000.0    Christian Bale   
4                       131.0                     NaN        Rob Walker   
...                       ...                     ...               ...   
4911                      2.0                   318.0     Daphne Zuniga   
4912                      NaN                   319.0     Valorie Curry   
4913                      0.0                     0.0     Maxwell Moody   
4914                      0.0                   489.0     Daniel Henney   
4915                     16.0                    16.0  Brian Herzlinger   

      actor_1_facebook_likes        gross  ... language country  \
0                     1000.0  760505847.0  ...  English     USA   
1                    40000.0  309404152.0  ...  English     USA   
2                    11000.0  200074175.0  ...  English      UK   
3                    27000.0  448130642.0  ...  English     USA   
4                      131.0          NaN  ...      NaN     NaN   
...                      ...          ...  ...      ...     ...   
4911                   637.0          NaN  ...  English  Canada   
4912                   841.0          NaN  ...  English     USA   
4913                     0.0          NaN  ...  English     USA   
4914                   946.0      10443.0  ...  English     USA   
4915                    86.0      85222.0  ...  English     USA   

     content_rating       budget  title_year actor_2_facebook_likes  \
0             PG-13  237000000.0      2009.0                  936.0   
1             PG-13  300000000.0      2007.0                 5000.0   
2             PG-13  245000000.0      2015.0                  393.0   
3             PG-13  250000000.0      2012.0                23000.0   
4               NaN          NaN         NaN                   12.0   
...             ...          ...         ...                    ...   
4911            NaN          NaN      2013.0                  470.0   
4912          TV-14          NaN         NaN                  593.0   
4913            NaN       1400.0      2013.0                    0.0   
4914          PG-13          NaN      2012.0                  719.0   
4915             PG       1100.0      2004.0                   23.0   

      imdb_score aspect_ratio movie_facebook_likes  has_seen  
0            7.9         1.78                33000         0  
1            7.1         2.35                    0         0  
2            6.8         2.35                85000         0  
3            8.5         2.35               164000         0  
4            7.1          NaN                    0         0  
...          ...          ...                  ...       ...  
4911         7.7          NaN                   84         0  
4912     

In [109]:
type(movie[['감독이름']])

pandas.core.frame.DataFrame

## 1. DataFrame 열 선택

### 1.1. 리스트를 사용한 열 선택

In [ ]:
movie = pd.read_csv('data/movie.csv')
movie.head()

In [ ]:
movie_actor = movie[['actor_1_name','actor_2_name','actor_3_name']]
movie_actor.head()

In [ ]:
movie[['director_name']].head()

In [ ]:
cols = ['actor_1_name','actor_2_name','actor_3_name']
movie[cols].head()

### 1.2. 메서드를 사용한 열 선택

In [ ]:
movie.get_dtype_counts() # 각 특정 데이터 형식의 열 개수 출력

In [ ]:
movie.select_dtypes(include=['int64']).head() # 정수열 만 선택

In [ ]:
# 수치로 된 모든 열 선택
movie.select_dtypes(include=['number']).head() 

In [ ]:
# 열 선택하는 또 다른 방법 filter
# facebook 이라는 문자열을 이름에 포함하고 있는 모든 열을 검색
movie.filter(like='facebook').head()

In [ ]:
# filter 메서드를 사용하면 regex 매개변수를 통해 정규식을 사용해
# 열을 검색가능, 여기서는 이름에 숫자가 포함되 있느 모든 열 검색
movie.filter(regex='\d').head()

## 2. 전체 DataFrame 연산

### 2.1. Series 속성과 메서드 사용

In [ ]:
# dataframe의 행(row)와 열(column) 개수를 가진 2개의 숫자를 
# tuple로 반환
movie.shape

In [ ]:
# dataframe의 전체원소 개수 반환
movie.size

In [ ]:
# 차원수 반환
movie.ndim

In [ ]:
# 행의 개수 반환
len(movie)

In [ ]:
# 각 열에 누락값을 제외한 개수
movie.count()

In [ ]:
movie.min() # max, mean, median, std

In [ ]:
# 앞단계에서 계산한 모든 기술 통계량과 분위수를 한꺼번에 계산
movie.describe() 

### 2.2. 메서드 체인 사용

In [ ]:
movie.isnull().head()

In [ ]:
movie.isnull().sum()

In [ ]:
movie.isnull().sum().sum()

In [ ]:
movie.isnull().any().any()

In [ ]:
# 백슬래시(\) 줄바꿈을 하지 못하게 하는 방법으로 
# 한줄의 하나의 메서드만 나열, 가독성을 높이고 중간에 주석을 달 수 있다
movie.select_dtypes(['object'])\
    .fillna('')\
    .max()

In [ ]:
(movie.select_dtypes(include=['number'])+0.00001).head()

In [ ]:
(movie.select_dtypes(include=['number'])+0.00001).round(-2).head()

## 3. 대학 캠퍼스의 다양성 지수 발견

In [ ]:
college = pd.read_csv('data/college.csv', index_col='INSTNM')
college_ug = college.filter(like='UGDS_')
college_ug.head()

In [ ]:
# sum(axis=1) : 열개수의 합
# sum(axis=0) : 행개수의 합
college_ug.isnull().sum(axis=0)

In [ ]:
(college_ug.isnull().sum(axis=0)>0).sum()

In [ ]:
college_ug.isnull().sum(axis=1)

In [ ]:
(college_ug.isnull().sum(axis=1)>0).sum()

In [ ]:
college_ug = college_ug.dropna(how='all')
college_ug.isnull().sum()

In [ ]:
diversity_metric = (college_ug>=0.15).sum(axis=1)
diversity_metric.head()

In [ ]:
diversity_metric.value_counts()

In [ ]:
diversity_metric.sort_values(ascending=False).head()

In [ ]:
diversity_metric.sort_values(ascending=False).head()