### tensor(텐서)
- 텐서는 배열(array)이나 행렬(matrix)과 매우 유사한 특수한 자료구조(data structure)이다.<br>
PyTorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)한다.
- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 `NumPy`의 `ndarray`와 유사하다.<br>
실제로 텐서와 `NumPy 배열(array)`은 종종 동일한 내부(underly) 메모리를 공유할 수 있어 데이터를 복사할 필요가 없다.<br>
텐서는 또한 자동 미분(automatic differentiation)에 최적화 되어 있다.<br>
`ndarray`에 익숙하다면 `Tensor API` 또한 쉽게 사용할 수 있을 것이다.

In [3]:
import torch
import numpy as np
torch.__version__

'1.13.0.dev20220915'

In [5]:
# 임의의 데이터로부터 직접 텐서 생성하기 - 이 때 데이터의 자료형을 따로 입력하지 않으면 자동으로 유추된다
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
np_array = np.array(data)

print(x_data, np_array, sep="\n")

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [7]:
# numpy 배열로부터 텐서 생성하기 - 텐서에서 넘파이 배열로도 가능
x_np = torch.from_numpy(np_array)
print(x_np)
to_np = x_np.numpy()
print(to_np)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [23]:
# 다른 텐서로부터 텐서 생성하기 - 명시적으로 재정의(overriding) 하지 않는다면,
# 인자(argument) 로 주어진 텐서의 속성(shape, dtype)을 유지한다.

# x_data -> 임의의 데이터로부터 생성된 텐서
print(type(x_data))
print(x_data.dtype)

x_ones = torch.ones_like(x_data)  # 입력 데이터의 속성을 유지함
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)  # 입력 데이터의 속성을 명시하여 덮어 씌움
print(x_rand)

<class 'torch.Tensor'>
torch.int64
tensor([[1, 1],
        [1, 1]])
tensor([[0.5088, 0.8424],
        [0.0607, 0.6890]])


In [24]:
# 무작위(random) 또는 상수(constant) 값을 텐서로써 사용하기
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.3683, 0.4223, 0.1018],
        [0.2091, 0.9842, 0.6533]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성(Attribute)
- 텐서의 속성은 모양(shape), 자료형(data type) 및 어느 장치(CPU or GPU)에 저장되는지를 나타낸다.

In [25]:
tensor = torch.rand(3,4)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([3, 4])
torch.float32
cpu


### 텐서의 연산(Operation)
- 전치, 인덱싱, 슬라이싱, 수학 계산, 선형 대수, 임의 샘플링 등 100가지 이상의 텐서 연산들은 [여기](https://pytorch.org/docs/stable/torch.html)에서 확인 가능

In [34]:
# GPU가 존재하면 텐서를 이동시킴
tensor = torch.rand(3,4)
if torch.cuda.is_available():
    # 기본적으로 텐서는 CPU에서 생성됨. 하지만 장치들 간에 큰 텐서들을 복사하는 것은
    # 시간과 메모리 측면에서 비용(cost)이 많이든다는 것을 기억하자
    tensor = tensor.to("cuda")
else:
    print("not available GPU")

print(tensor, tensor.dtype)
print(tensor.tolist())

not available GPU
tensor([[0.6016, 0.6248, 0.8897, 0.0635],
        [0.9292, 0.5868, 0.1256, 0.3579],
        [0.4259, 0.7948, 0.7762, 0.7429]]) torch.float32
[[0.6016283631324768, 0.6248472332954407, 0.8896991610527039, 0.06352609395980835], [0.9292129874229431, 0.5867754220962524, 0.1255967617034912, 0.35789698362350464], [0.42592257261276245, 0.7947680354118347, 0.7762494087219238, 0.7429388761520386]]


#### 인덱싱과 슬라이싱

In [39]:
# NumPy식의 표준 인덱싱과 슬라이싱과 같은 방식으로 동작한다.
tensor = torch.ones(4, 4)
print(tensor)
print(f"first row: {tensor[0]}")
print(f"first column: {tensor[:, 0]}")
# print(f"last column: {tensor[:, -1]}")
print(f"last column: {tensor[..., -1]}")

# 두번째 열을 0으로 교체
tensor[:, 1] = 0
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
first row: tensor([1., 1., 1., 1.])
first column: tensor([1., 1., 1., 1.])
last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### 텐서 합치기

In [56]:
# 텐서 합치기(torch.cat)를 사용하여 주어진 차원(dimension)에 따라 일련의 텐서를 연결할 수 있다.
tensor = torch.rand(2, 2)
print(tensor)

t1 = torch.cat([tensor, tensor, tensor], dim=0)  # dim=0 -> 행으로 결합, dim=1 -> 열로 결합
print(t1)

# torch.cat 과 미묘하게 다른 또다른 텐서 결합 연산인 torch.stack도 있다.
t2 = torch.stack([tensor, tensor, tensor], dim=0)
print(t2)

tensor([[0.3196, 0.6250],
        [0.3493, 0.9406]])
tensor([[0.3196, 0.6250],
        [0.3493, 0.9406],
        [0.3196, 0.6250],
        [0.3493, 0.9406],
        [0.3196, 0.6250],
        [0.3493, 0.9406]])
tensor([[[0.3196, 0.6250],
         [0.3493, 0.9406]],

        [[0.3196, 0.6250],
         [0.3493, 0.9406]],

        [[0.3196, 0.6250],
         [0.3493, 0.9406]]])


#### 산술 연산(Arithmetic Operations)

In [69]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산
tensor = torch.ones(4, 4)
tensor[:, 1] = 0
print(tensor, tensor.T)
print()

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)
print(y2)

y3 = torch.rand_like(y1)
print(torch.matmul(tensor, tensor.T, out=y3))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) tensor([[1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [70]:
# 요소별 곱(element-wise product)을 계산
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)
print(z2)

z3 = torch.rand_like(tensor)
print(torch.mul(tensor, tensor, out=z3))

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


#### 단일 요소 텐서 변환

In [71]:
# 단일-요소(single-element) 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우,
# item() 메서드를 사용하여 python 숫자 값으로 변환할 수 있다.
tensor = torch.ones(4, 4)
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

16.0 <class 'float'>


#### 바꿔치기(in-place) 연산

In [72]:
# 바꿔치기 연산은 연산 결과를 피연산자(operand)에 저장하는 연산, 메서드 뒤에 접미사 _ 를 갖는다.
tensor = torch.ones(4, 4)
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


#### 참조 변환(Reference Bridge)

In [74]:
# tensor -> numpy, 텐서 바꿔치기 연산
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
t.add_(1)
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [81]:
# numpy -> tensor, 넘파이 바꿔치기 연산
n = np.ones(5)
print(n)
t = torch.from_numpy(n)
# t = torch.tensor(n)  # torch.tensor 를 사용하여 텐서로 변환할수도 있지만, 더이상 넘파이를 참조하지 않는다.
print(t)
np.add(n, 1, out=n)
print(n)
print(t)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
