### tensor(텐서)

In [3]:
import torch
import numpy as np
torch.__version__

'1.13.0.dev20220915'

In [5]:
# 임의의 데이터로부터 직접 텐서 생성하기 - 이 때 데이터의 자료형을 따로 입력하지 않으면 자동으로 유추된다
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
np_array = np.array(data)

print(x_data, np_array, sep="\n")

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [7]:
# numpy 배열로부터 텐서 생성하기 - 텐서에서 넘파이 배열로도 가능
x_np = torch.from_numpy(np_array)
print(x_np)
to_np = x_np.numpy()
print(to_np)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]


In [23]:
# 다른 텐서로부터 텐서 생성하기 - 명시적으로 재정의(overriding) 하지 않는다면,
# 인자(argument) 로 주어진 텐서의 속성(shape, dtype)을 유지한다.

# x_data -> 임의의 데이터로부터 생성된 텐서
print(type(x_data))
print(x_data.dtype)

x_ones = torch.ones_like(x_data)  # 입력 데이터의 속성을 유지함
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)  # 입력 데이터의 속성을 명시하여 덮어 씌움
print(x_rand)

<class 'torch.Tensor'>
torch.int64
tensor([[1, 1],
        [1, 1]])
tensor([[0.5088, 0.8424],
        [0.0607, 0.6890]])


In [24]:
# 무작위(random) 또는 상수(constant) 값을 텐서로써 사용하기
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.3683, 0.4223, 0.1018],
        [0.2091, 0.9842, 0.6533]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### 텐서의 속성(Attribute)